//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class derstablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public derstablo()
        {
            this.ogrenciderstablo = new HashSet<ogrenciderstablo>();
        }
    
        public short dersid { get; set; }
        public string dersadi { get; set; }
        public string derskredisi { get; set; }
        public Nullable<short> dersokulyonetimid { get; set; }
    
        public virtual okulyonetimtablo okulyonetimtablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciderstablo> ogrenciderstablo { get; set; }
    }
}
