//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrencilertablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrencilertablo()
        {
            this.ogrenciderstablo = new HashSet<ogrenciderstablo>();
        }
    
        public short ogrenciid { get; set; }
        public string ogrenciadsoyad { get; set; }
        public Nullable<System.DateTime> ogrencikayittarih { get; set; }
        public Nullable<System.DateTime> ogrencidogumtarih { get; set; }
        public string ogrencibolum { get; set; }
        public string ogrencino { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenciderstablo> ogrenciderstablo { get; set; }
    }
}
