//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class okulyonetimtablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public okulyonetimtablo()
        {
            this.derstablo = new HashSet<derstablo>();
        }
    
        public short yonetimid { get; set; }
        public string yonetimadsoyad { get; set; }
        public string yonetimgorevi { get; set; }
        public string yonetimtipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<derstablo> derstablo { get; set; }
    }
}
